FROM node AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
RUN npm install -g serve

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

ARG FRONTEND_PORT
ARG FRONTEND_PORT_PROD

ENV FRONTEND_PORT=${FRONTEND_PORT}
ENV FRONTEND_PORT_PROD=${FRONTEND_PORT_PROD}
EXPOSE 80
EXPOSE ${FRONTEND_PORT}
EXPOSE ${FRONTEND_PORT_PROD}

CMD ["serve", "-s", "build", "-l", "${FRONTEND_PORT_PROD}"]
